use std::fmt;
use serde::{de, Deserialize, ser, Serialize};
/**26

See docs at <https://www.stedi.com/edi/x12-005010/element/26>*/
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CountryCode {
    ///ABW, AW - Aruba
    Aruba,
    ///AD, AND - Andorra
    Andorra,
    ///AE, ARE - United Arab Emirates (the)
    CodeAE,
    ///AF, AFG - Afghanistan
    Afghanistan,
    ///AG, ATG - Antigua and Barbuda
    AntiguaAndBarbuda,
    ///AGO, AO - Angola
    Angola,
    ///AI, AIA - Anguilla
    Anguilla,
    ///AL, ALB - Albania
    Albania,
    ///ALA, AX - Åland Islands
    ÅlandIslands,
    ///AM, ARM - Armenia
    Armenia,
    ///AQ, ATA - Antarctica
    Antarctica,
    ///AR, ARG - Argentina
    Argentina,
    ///AS, ASM - American Samoa
    AmericanSamoa,
    ///AT, AUT - Austria
    Austria,
    ///ATF, TF - French Southern Territories (the)
    CodeATF,
    ///AU, AUS - Australia
    Australia,
    ///AZ, AZE - Azerbaijan
    Azerbaijan,
    ///BA, BIH - Bosnia and Herzegovina
    BosniaAndHerzegovina,
    ///BB, BRB - Barbados
    Barbados,
    ///BD, BGD - Bangladesh
    Bangladesh,
    ///BDI, BI - Burundi
    Burundi,
    ///BE, BEL - Belgium
    Belgium,
    ///BEN, BJ - Benin
    Benin,
    ///BES, BQ - Bonaire, Sint Eustatius and Saba
    CodeBES,
    ///BF, BFA - Burkina Faso
    BurkinaFaso,
    ///BG, BGR - Bulgaria
    Bulgaria,
    ///BH, BHR - Bahrain
    Bahrain,
    ///BHS, BS - Bahamas (the)
    CodeBHS,
    ///BL, BLM - Saint Barthélemy
    SaintBarthelemy,
    ///BLR, BY - Belarus
    Belarus,
    ///BLZ, BZ - Belize
    Belize,
    ///BM, BMU - Bermuda
    Bermuda,
    ///BN, BRN - Brunei Darussalam
    BruneiDarussalam,
    ///BO, BOL - Bolivia (Plurinational State of)
    CodeBO,
    ///BR, BRA - Brazil
    Brazil,
    ///BT, BTN - Bhutan
    Bhutan,
    ///BV, BVT - Bouvet Island
    BouvetIsland,
    ///BW, BWA - Botswana
    Botswana,
    ///CA, CAN - Canada
    Canada,
    ///CAF, CF - Central African Republic (the)
    CodeCAF,
    ///CC, CCK - Cocos (Keeling) Islands (the)
    CodeCC,
    ///CD, COD - Congo (the Democratic Republic of the)
    CodeCD,
    ///CG, COG - Congo (the)
    CodeCG,
    ///CH, CHE - Switzerland
    Switzerland,
    ///CHL, CL - Chile
    Chile,
    ///CHN, CN - China
    China,
    ///CI, CIV - Côte d'Ivoire
    CôteDIvoire,
    ///CK, COK - Cook Islands (the)
    CodeCK,
    ///CM, CMR - Cameroon
    Cameroon,
    ///CO, COL - Colombia
    Colombia,
    ///COM, KM - Comoros (the)
    CodeCOM,
    ///CPV, CV - Cabo Verde
    CaboVerde,
    ///CR, CRI - Costa Rica
    CostaRica,
    ///CU, CUB - Cuba
    Cuba,
    ///CUW, CW - Curaçao
    Curaçao,
    ///CX, CXR - Christmas Island
    ChristmasIsland,
    ///CY, CYP - Cyprus
    Cyprus,
    ///CYM, KY - Cayman Islands (the)
    CodeCYM,
    ///CZ, CZE - Czechia
    Czechia,
    ///DE, DEU - Germany
    Germany,
    ///DJ, DJI - Djibouti
    Djibouti,
    ///DK, DNK - Denmark
    Denmark,
    ///DM, DMA - Dominica
    Dominica,
    ///DO, DOM - Dominican Republic (the)
    CodeDO,
    ///DZ, DZA - Algeria
    Algeria,
    ///EC, ECU - Ecuador
    Ecuador,
    ///EE, EST - Estonia
    Estonia,
    ///EG, EGY - Egypt
    Egypt,
    ///EH, ESH - Western Sahara*
    CodeEH,
    ///ER, ERI - Eritrea
    Eritrea,
    ///ES, ESP - Spain
    Spain,
    ///ET, ETH - Ethiopia
    Ethiopia,
    ///FI, FIN - Finland
    Finland,
    ///FJ, FJI - Fiji
    Fiji,
    ///FK, FLK - Falkland Islands (the) [Malvinas]
    CodeFK,
    ///FM, FSM - Micronesia (Federated States of)
    CodeFM,
    ///FO, FRO - Faroe Islands (the)
    CodeFO,
    ///FR, FRA - France
    France,
    ///GA, GAB - Gabon
    Gabon,
    ///GB, GBR - United Kingdom of Great Britain and Northern Ireland (the)
    CodeGB,
    ///GD, GRD - Grenada
    Grenada,
    ///GE, GEO - Georgia
    Georgia,
    ///GF, GUF - French Guiana
    FrenchGuiana,
    ///GG, GGY - Guernsey
    Guernsey,
    ///GH, GHA - Ghana
    Ghana,
    ///GI, GIB - Gibraltar
    Gibraltar,
    ///GIN, GN - Guinea
    Guinea,
    ///GL, GRL - Greenland
    Greenland,
    ///GLP, GP - Guadeloupe
    Guadeloupe,
    ///GM, GMB - Gambia (the)
    CodeGM,
    ///GNB, GW - Guinea-Bissau
    GuineaBissau,
    ///GNQ, GQ - Equatorial Guinea
    EquatorialGuinea,
    ///GR, GRC - Greece
    Greece,
    ///GS, SGS - South Georgia and the South Sandwich Islands
    SouthGeorgiaAndTheSouthSandwichIslands,
    ///GT, GTM - Guatemala
    Guatemala,
    ///GU, GUM - Guam
    Guam,
    ///GUY, GY - Guyana
    Guyana,
    ///HK, HKG - Hong Kong
    HongKong,
    ///HM, HMD - Heard Island and McDonald Islands
    HeardIslandAndMcDonaldIslands,
    ///HN, HND - Honduras
    Honduras,
    ///HR, HRV - Croatia
    Croatia,
    ///HT, HTI - Haiti
    Haiti,
    ///HU, HUN - Hungary
    Hungary,
    ///ID, IDN - Indonesia
    Indonesia,
    ///IE, IRL - Ireland
    Ireland,
    ///IL, ISR - Israel
    Israel,
    ///IM, IMN - Isle of Man
    IsleOfMan,
    ///IN, IND - India
    India,
    ///IO, IOT - British Indian Ocean Territory (the)
    CodeIO,
    ///IQ, IRQ - Iraq
    Iraq,
    ///IR, IRN - Iran (Islamic Republic of)
    CodeIR,
    ///IS, ISL - Iceland
    Iceland,
    ///IT, ITA - Italy
    Italy,
    ///JAM, JM - Jamaica
    Jamaica,
    ///JE, JEY - Jersey
    Jersey,
    ///JO, JOR - Jordan
    Jordan,
    ///JP, JPN - Japan
    Japan,
    ///KAZ, KZ - Kazakhstan
    Kazakhstan,
    ///KE, KEN - Kenya
    Kenya,
    ///KG, KGZ - Kyrgyzstan
    Kyrgyzstan,
    ///KH, KHM - Cambodia
    Cambodia,
    ///KI, KIR - Kiribati
    Kiribati,
    ///KN, KNA - Saint Kitts and Nevis
    SaintKittsAndNevis,
    ///KOR, KR - Korea (the Republic of)
    CodeKOR,
    ///KP, PRK - Korea (the Democratic People's Republic of)
    CodeKP,
    ///KW, KWT - Kuwait
    Kuwait,
    ///LA, LAO - Lao People's Democratic Republic (the)
    CodeLA,
    ///LB, LBN - Lebanon
    Lebanon,
    ///LBR, LR - Liberia
    Liberia,
    ///LBY, LY - Libya
    Libya,
    ///LC, LCA - Saint Lucia
    SaintLucia,
    ///LI, LIE - Liechtenstein
    Liechtenstein,
    ///LK, LKA - Sri Lanka
    SriLanka,
    ///LS, LSO - Lesotho
    Lesotho,
    ///LT, LTU - Lithuania
    Lithuania,
    ///LU, LUX - Luxembourg
    Luxembourg,
    ///LV, LVA - Latvia
    Latvia,
    ///MA, MAR - Morocco
    Morocco,
    ///MAC, MO - Macao
    Macao,
    ///MAF, MF - Saint Martin (French part)
    CodeMAF,
    ///MC, MCO - Monaco
    Monaco,
    ///MD, MDA - Moldova (the Republic of)
    CodeMD,
    ///MDG, MG - Madagascar
    Madagascar,
    ///MDV, MV - Maldives
    Maldives,
    ///ME, MNE - Montenegro
    Montenegro,
    ///MEX, MX - Mexico
    Mexico,
    ///MH, MHL - Marshall Islands (the)
    CodeMH,
    ///MK, MKD - North Macedonia
    NorthMacedonia,
    ///ML, MLI - Mali
    Mali,
    ///MLT, MT - Malta
    Malta,
    ///MM, MMR - Myanmar
    Myanmar,
    ///MN, MNG - Mongolia
    Mongolia,
    ///MNP, MP - Northern Mariana Islands (the)
    CodeMNP,
    ///MOZ, MZ - Mozambique
    Mozambique,
    ///MQ, MTQ - Martinique
    Martinique,
    ///MR, MRT - Mauritania
    Mauritania,
    ///MS, MSR - Montserrat
    Montserrat,
    ///MU, MUS - Mauritius
    Mauritius,
    ///MW, MWI - Malawi
    Malawi,
    ///MY, MYS - Malaysia
    Malaysia,
    ///MYT, YT - Mayotte
    Mayotte,
    ///NA, NAM - Namibia
    Namibia,
    ///NC, NCL - New Caledonia
    NewCaledonia,
    ///NE, NER - Niger (the)
    CodeNE,
    ///NF, NFK - Norfolk Island
    NorfolkIsland,
    ///NG, NGA - Nigeria
    Nigeria,
    ///NI, NIC - Nicaragua
    Nicaragua,
    ///NIU, NU - Niue
    Niue,
    ///NL, NLD - Netherlands (the)
    CodeNL,
    ///NO, NOR - Norway
    Norway,
    ///NP, NPL - Nepal
    Nepal,
    ///NR, NRU - Nauru
    Nauru,
    ///NZ, NZL - New Zealand
    NewZealand,
    ///OM, OMN - Oman
    Oman,
    ///PA, PAN - Panama
    Panama,
    ///PAK, PK - Pakistan
    Pakistan,
    ///PCN, PN - Pitcairn
    Pitcairn,
    ///PE, PER - Peru
    Peru,
    ///PF, PYF - French Polynesia
    FrenchPolynesia,
    ///PG, PNG - Papua New Guinea
    PapuaNewGuinea,
    ///PH, PHL - Philippines (the)
    CodePH,
    ///PL, POL - Poland
    Poland,
    ///PLW, PW - Palau
    Palau,
    ///PM, SPM - Saint Pierre and Miquelon
    SaintPierreAndMiquelon,
    ///PR, PRI - Puerto Rico
    PuertoRico,
    ///PRT, PT - Portugal
    Portugal,
    ///PRY, PY - Paraguay
    Paraguay,
    ///PS, PSE - Palestine, State of
    CodePS,
    ///QA, QAT - Qatar
    Qatar,
    ///RE, REU - Réunion
    Reunion,
    ///RO, ROU - Romania
    Romania,
    ///RS, SRB - Serbia
    Serbia,
    ///RU, RUS - Russian Federation (the)
    CodeRU,
    ///RW, RWA - Rwanda
    Rwanda,
    ///SA, SAU - Saudi Arabia
    SaudiArabia,
    ///SB, SLB - Solomon Islands
    SolomonIslands,
    ///SC, SYC - Seychelles
    Seychelles,
    ///SD, SDN - Sudan (the)
    CodeSD,
    ///SE, SWE - Sweden
    Sweden,
    ///SEN, SN - Senegal
    Senegal,
    ///SG, SGP - Singapore
    Singapore,
    ///SH, SHN - Saint Helena, Ascension and Tristan da Cunha
    CodeSH,
    ///SI, SVN - Slovenia
    Slovenia,
    ///SJ, SJM - Svalbard and Jan Mayen
    SvalbardAndJanMayen,
    ///SK, SVK - Slovakia
    Slovakia,
    ///SL, SLE - Sierra Leone
    SierraLeone,
    ///SLV, SV - El Salvador
    ElSalvador,
    ///SM, SMR - San Marino
    SanMarino,
    ///SO, SOM - Somalia
    Somalia,
    ///SR, SUR - Suriname
    Suriname,
    ///SS, SSD - South Sudan
    SouthSudan,
    ///ST, STP - Sao Tome and Principe
    SaoTomeAndPrincipe,
    ///SWZ, SZ - Eswatini
    Eswatini,
    ///SX, SXM - Sint Maarten (Dutch part)
    CodeSX,
    ///SY, SYR - Syrian Arab Republic (the)
    CodeSY,
    ///TC, TCA - Turks and Caicos Islands (the)
    CodeTC,
    ///TCD, TD - Chad
    Chad,
    ///TG, TGO - Togo
    Togo,
    ///TH, THA - Thailand
    Thailand,
    ///TJ, TJK - Tajikistan
    Tajikistan,
    ///TK, TKL - Tokelau
    Tokelau,
    ///TKM, TM - Turkmenistan
    Turkmenistan,
    ///TL, TLS - Timor-Leste
    TimorLeste,
    ///TN, TUN - Tunisia
    Tunisia,
    ///TO, TON - Tonga
    Tonga,
    ///TR, TUR - Türkiye
    Türkiye,
    ///TT, TTO - Trinidad and Tobago
    TrinidadAndTobago,
    ///TUV, TV - Tuvalu
    Tuvalu,
    ///TW, TWN - Taiwan (Province of China)
    CodeTW,
    ///TZ, TZA - Tanzania, the United Republic of
    CodeTZ,
    ///UA, UKR - Ukraine
    Ukraine,
    ///UG, UGA - Uganda
    Uganda,
    ///UM, UMI - United States Minor Outlying Islands (the)
    CodeUM,
    ///URY, UY - Uruguay
    Uruguay,
    ///US, USA - United States of America (the)
    CodeUS,
    ///UZ, UZB - Uzbekistan
    Uzbekistan,
    ///VA, VAT - Holy See (the)
    CodeVA,
    ///VC, VCT - Saint Vincent and the Grenadines
    SaintVincentAndTheGrenadines,
    ///VE, VEN - Venezuela (Bolivarian Republic of)
    CodeVE,
    ///VG, VGB - Virgin Islands (British)
    CodeVG,
    ///VI, VIR - Virgin Islands (U.S.)
    CodeVI,
    ///VN, VNM - Viet Nam
    VietNam,
    ///VU, VUT - Vanuatu
    Vanuatu,
    ///WF, WLF - Wallis and Futuna
    WallisAndFutuna,
    ///WS, WSM - Samoa
    Samoa,
    ///YE, YEM - Yemen
    Yemen,
    ///ZA, ZAF - South Africa
    SouthAfrica,
    ///ZM, ZMB - Zambia
    Zambia,
    ///ZW, ZWE - Zimbabwe
    Zimbabwe,
}
impl CountryCode {
    pub fn code(&self) -> &str {
        {
            use CountryCode::*;
            match self {
                Aruba => "ABW",
                Andorra => "AD",
                CodeAE => "AE",
                Afghanistan => "AF",
                AntiguaAndBarbuda => "AG",
                Angola => "AGO",
                Anguilla => "AI",
                Albania => "AL",
                ÅlandIslands => "ALA",
                Armenia => "AM",
                Antarctica => "AQ",
                Argentina => "AR",
                AmericanSamoa => "AS",
                Austria => "AT",
                CodeATF => "ATF",
                Australia => "AU",
                Azerbaijan => "AZ",
                BosniaAndHerzegovina => "BA",
                Barbados => "BB",
                Bangladesh => "BD",
                Burundi => "BDI",
                Belgium => "BE",
                Benin => "BEN",
                CodeBES => "BES",
                BurkinaFaso => "BF",
                Bulgaria => "BG",
                Bahrain => "BH",
                CodeBHS => "BHS",
                SaintBarthelemy => "BL",
                Belarus => "BLR",
                Belize => "BLZ",
                Bermuda => "BM",
                BruneiDarussalam => "BN",
                CodeBO => "BO",
                Brazil => "BR",
                Bhutan => "BT",
                BouvetIsland => "BV",
                Botswana => "BW",
                Canada => "CA",
                CodeCAF => "CAF",
                CodeCC => "CC",
                CodeCD => "CD",
                CodeCG => "CG",
                Switzerland => "CH",
                Chile => "CHL",
                China => "CHN",
                CôteDIvoire => "CI",
                CodeCK => "CK",
                Cameroon => "CM",
                Colombia => "CO",
                CodeCOM => "COM",
                CaboVerde => "CPV",
                CostaRica => "CR",
                Cuba => "CU",
                Curaçao => "CUW",
                ChristmasIsland => "CX",
                Cyprus => "CY",
                CodeCYM => "CYM",
                Czechia => "CZ",
                Germany => "DE",
                Djibouti => "DJ",
                Denmark => "DK",
                Dominica => "DM",
                CodeDO => "DO",
                Algeria => "DZ",
                Ecuador => "EC",
                Estonia => "EE",
                Egypt => "EG",
                CodeEH => "EH",
                Eritrea => "ER",
                Spain => "ES",
                Ethiopia => "ET",
                Finland => "FI",
                Fiji => "FJ",
                CodeFK => "FK",
                CodeFM => "FM",
                CodeFO => "FO",
                France => "FR",
                Gabon => "GA",
                CodeGB => "GB",
                Grenada => "GD",
                Georgia => "GE",
                FrenchGuiana => "GF",
                Guernsey => "GG",
                Ghana => "GH",
                Gibraltar => "GI",
                Guinea => "GIN",
                Greenland => "GL",
                Guadeloupe => "GLP",
                CodeGM => "GM",
                GuineaBissau => "GNB",
                EquatorialGuinea => "GNQ",
                Greece => "GR",
                SouthGeorgiaAndTheSouthSandwichIslands => "GS",
                Guatemala => "GT",
                Guam => "GU",
                Guyana => "GUY",
                HongKong => "HK",
                HeardIslandAndMcDonaldIslands => "HM",
                Honduras => "HN",
                Croatia => "HR",
                Haiti => "HT",
                Hungary => "HU",
                Indonesia => "ID",
                Ireland => "IE",
                Israel => "IL",
                IsleOfMan => "IM",
                India => "IN",
                CodeIO => "IO",
                Iraq => "IQ",
                CodeIR => "IR",
                Iceland => "IS",
                Italy => "IT",
                Jamaica => "JAM",
                Jersey => "JE",
                Jordan => "JO",
                Japan => "JP",
                Kazakhstan => "KAZ",
                Kenya => "KE",
                Kyrgyzstan => "KG",
                Cambodia => "KH",
                Kiribati => "KI",
                SaintKittsAndNevis => "KN",
                CodeKOR => "KOR",
                CodeKP => "KP",
                Kuwait => "KW",
                CodeLA => "LA",
                Lebanon => "LB",
                Liberia => "LBR",
                Libya => "LBY",
                SaintLucia => "LC",
                Liechtenstein => "LI",
                SriLanka => "LK",
                Lesotho => "LS",
                Lithuania => "LT",
                Luxembourg => "LU",
                Latvia => "LV",
                Morocco => "MA",
                Macao => "MAC",
                CodeMAF => "MAF",
                Monaco => "MC",
                CodeMD => "MD",
                Madagascar => "MDG",
                Maldives => "MDV",
                Montenegro => "ME",
                Mexico => "MEX",
                CodeMH => "MH",
                NorthMacedonia => "MK",
                Mali => "ML",
                Malta => "MLT",
                Myanmar => "MM",
                Mongolia => "MN",
                CodeMNP => "MNP",
                Mozambique => "MOZ",
                Martinique => "MQ",
                Mauritania => "MR",
                Montserrat => "MS",
                Mauritius => "MU",
                Malawi => "MW",
                Malaysia => "MY",
                Mayotte => "MYT",
                Namibia => "NA",
                NewCaledonia => "NC",
                CodeNE => "NE",
                NorfolkIsland => "NF",
                Nigeria => "NG",
                Nicaragua => "NI",
                Niue => "NIU",
                CodeNL => "NL",
                Norway => "NO",
                Nepal => "NP",
                Nauru => "NR",
                NewZealand => "NZ",
                Oman => "OM",
                Panama => "PA",
                Pakistan => "PAK",
                Pitcairn => "PCN",
                Peru => "PE",
                FrenchPolynesia => "PF",
                PapuaNewGuinea => "PG",
                CodePH => "PH",
                Poland => "PL",
                Palau => "PLW",
                SaintPierreAndMiquelon => "PM",
                PuertoRico => "PR",
                Portugal => "PRT",
                Paraguay => "PRY",
                CodePS => "PS",
                Qatar => "QA",
                Reunion => "RE",
                Romania => "RO",
                Serbia => "RS",
                CodeRU => "RU",
                Rwanda => "RW",
                SaudiArabia => "SA",
                SolomonIslands => "SB",
                Seychelles => "SC",
                CodeSD => "SD",
                Sweden => "SE",
                Senegal => "SEN",
                Singapore => "SG",
                CodeSH => "SH",
                Slovenia => "SI",
                SvalbardAndJanMayen => "SJ",
                Slovakia => "SK",
                SierraLeone => "SL",
                ElSalvador => "SLV",
                SanMarino => "SM",
                Somalia => "SO",
                Suriname => "SR",
                SouthSudan => "SS",
                SaoTomeAndPrincipe => "ST",
                Eswatini => "SWZ",
                CodeSX => "SX",
                CodeSY => "SY",
                CodeTC => "TC",
                Chad => "TCD",
                Togo => "TG",
                Thailand => "TH",
                Tajikistan => "TJ",
                Tokelau => "TK",
                Turkmenistan => "TKM",
                TimorLeste => "TL",
                Tunisia => "TN",
                Tonga => "TO",
                Türkiye => "TR",
                TrinidadAndTobago => "TT",
                Tuvalu => "TUV",
                CodeTW => "TW",
                CodeTZ => "TZ",
                Ukraine => "UA",
                Uganda => "UG",
                CodeUM => "UM",
                Uruguay => "URY",
                CodeUS => "US",
                Uzbekistan => "UZ",
                CodeVA => "VA",
                SaintVincentAndTheGrenadines => "VC",
                CodeVE => "VE",
                CodeVG => "VG",
                CodeVI => "VI",
                VietNam => "VN",
                Vanuatu => "VU",
                WallisAndFutuna => "WF",
                Samoa => "WS",
                Yemen => "YE",
                SouthAfrica => "ZA",
                Zambia => "ZM",
                Zimbabwe => "ZW",
            }
        }
    }
    pub fn from_code(code: &[u8]) -> Option<CountryCode> {
        use CountryCode::*;
        match code {
            b"ABW" => Some(Aruba),
            b"AW" => Some(Aruba),
            b"AD" => Some(Andorra),
            b"AND" => Some(Andorra),
            b"AE" => Some(CodeAE),
            b"ARE" => Some(CodeAE),
            b"AF" => Some(Afghanistan),
            b"AFG" => Some(Afghanistan),
            b"AG" => Some(AntiguaAndBarbuda),
            b"ATG" => Some(AntiguaAndBarbuda),
            b"AGO" => Some(Angola),
            b"AO" => Some(Angola),
            b"AI" => Some(Anguilla),
            b"AIA" => Some(Anguilla),
            b"AL" => Some(Albania),
            b"ALB" => Some(Albania),
            b"ALA" => Some(ÅlandIslands),
            b"AX" => Some(ÅlandIslands),
            b"AM" => Some(Armenia),
            b"ARM" => Some(Armenia),
            b"AQ" => Some(Antarctica),
            b"ATA" => Some(Antarctica),
            b"AR" => Some(Argentina),
            b"ARG" => Some(Argentina),
            b"AS" => Some(AmericanSamoa),
            b"ASM" => Some(AmericanSamoa),
            b"AT" => Some(Austria),
            b"AUT" => Some(Austria),
            b"ATF" => Some(CodeATF),
            b"TF" => Some(CodeATF),
            b"AU" => Some(Australia),
            b"AUS" => Some(Australia),
            b"AZ" => Some(Azerbaijan),
            b"AZE" => Some(Azerbaijan),
            b"BA" => Some(BosniaAndHerzegovina),
            b"BIH" => Some(BosniaAndHerzegovina),
            b"BB" => Some(Barbados),
            b"BRB" => Some(Barbados),
            b"BD" => Some(Bangladesh),
            b"BGD" => Some(Bangladesh),
            b"BDI" => Some(Burundi),
            b"BI" => Some(Burundi),
            b"BE" => Some(Belgium),
            b"BEL" => Some(Belgium),
            b"BEN" => Some(Benin),
            b"BJ" => Some(Benin),
            b"BES" => Some(CodeBES),
            b"BQ" => Some(CodeBES),
            b"BF" => Some(BurkinaFaso),
            b"BFA" => Some(BurkinaFaso),
            b"BG" => Some(Bulgaria),
            b"BGR" => Some(Bulgaria),
            b"BH" => Some(Bahrain),
            b"BHR" => Some(Bahrain),
            b"BHS" => Some(CodeBHS),
            b"BS" => Some(CodeBHS),
            b"BL" => Some(SaintBarthelemy),
            b"BLM" => Some(SaintBarthelemy),
            b"BLR" => Some(Belarus),
            b"BY" => Some(Belarus),
            b"BLZ" => Some(Belize),
            b"BZ" => Some(Belize),
            b"BM" => Some(Bermuda),
            b"BMU" => Some(Bermuda),
            b"BN" => Some(BruneiDarussalam),
            b"BRN" => Some(BruneiDarussalam),
            b"BO" => Some(CodeBO),
            b"BOL" => Some(CodeBO),
            b"BR" => Some(Brazil),
            b"BRA" => Some(Brazil),
            b"BT" => Some(Bhutan),
            b"BTN" => Some(Bhutan),
            b"BV" => Some(BouvetIsland),
            b"BVT" => Some(BouvetIsland),
            b"BW" => Some(Botswana),
            b"BWA" => Some(Botswana),
            b"CA" => Some(Canada),
            b"CAN" => Some(Canada),
            b"CAF" => Some(CodeCAF),
            b"CF" => Some(CodeCAF),
            b"CC" => Some(CodeCC),
            b"CCK" => Some(CodeCC),
            b"CD" => Some(CodeCD),
            b"COD" => Some(CodeCD),
            b"CG" => Some(CodeCG),
            b"COG" => Some(CodeCG),
            b"CH" => Some(Switzerland),
            b"CHE" => Some(Switzerland),
            b"CHL" => Some(Chile),
            b"CL" => Some(Chile),
            b"CHN" => Some(China),
            b"CN" => Some(China),
            b"CI" => Some(CôteDIvoire),
            b"CIV" => Some(CôteDIvoire),
            b"CK" => Some(CodeCK),
            b"COK" => Some(CodeCK),
            b"CM" => Some(Cameroon),
            b"CMR" => Some(Cameroon),
            b"CO" => Some(Colombia),
            b"COL" => Some(Colombia),
            b"COM" => Some(CodeCOM),
            b"KM" => Some(CodeCOM),
            b"CPV" => Some(CaboVerde),
            b"CV" => Some(CaboVerde),
            b"CR" => Some(CostaRica),
            b"CRI" => Some(CostaRica),
            b"CU" => Some(Cuba),
            b"CUB" => Some(Cuba),
            b"CUW" => Some(Curaçao),
            b"CW" => Some(Curaçao),
            b"CX" => Some(ChristmasIsland),
            b"CXR" => Some(ChristmasIsland),
            b"CY" => Some(Cyprus),
            b"CYP" => Some(Cyprus),
            b"CYM" => Some(CodeCYM),
            b"KY" => Some(CodeCYM),
            b"CZ" => Some(Czechia),
            b"CZE" => Some(Czechia),
            b"DE" => Some(Germany),
            b"DEU" => Some(Germany),
            b"DJ" => Some(Djibouti),
            b"DJI" => Some(Djibouti),
            b"DK" => Some(Denmark),
            b"DNK" => Some(Denmark),
            b"DM" => Some(Dominica),
            b"DMA" => Some(Dominica),
            b"DO" => Some(CodeDO),
            b"DOM" => Some(CodeDO),
            b"DZ" => Some(Algeria),
            b"DZA" => Some(Algeria),
            b"EC" => Some(Ecuador),
            b"ECU" => Some(Ecuador),
            b"EE" => Some(Estonia),
            b"EST" => Some(Estonia),
            b"EG" => Some(Egypt),
            b"EGY" => Some(Egypt),
            b"EH" => Some(CodeEH),
            b"ESH" => Some(CodeEH),
            b"ER" => Some(Eritrea),
            b"ERI" => Some(Eritrea),
            b"ES" => Some(Spain),
            b"ESP" => Some(Spain),
            b"ET" => Some(Ethiopia),
            b"ETH" => Some(Ethiopia),
            b"FI" => Some(Finland),
            b"FIN" => Some(Finland),
            b"FJ" => Some(Fiji),
            b"FJI" => Some(Fiji),
            b"FK" => Some(CodeFK),
            b"FLK" => Some(CodeFK),
            b"FM" => Some(CodeFM),
            b"FSM" => Some(CodeFM),
            b"FO" => Some(CodeFO),
            b"FRO" => Some(CodeFO),
            b"FR" => Some(France),
            b"FRA" => Some(France),
            b"GA" => Some(Gabon),
            b"GAB" => Some(Gabon),
            b"GB" => Some(CodeGB),
            b"GBR" => Some(CodeGB),
            b"GD" => Some(Grenada),
            b"GRD" => Some(Grenada),
            b"GE" => Some(Georgia),
            b"GEO" => Some(Georgia),
            b"GF" => Some(FrenchGuiana),
            b"GUF" => Some(FrenchGuiana),
            b"GG" => Some(Guernsey),
            b"GGY" => Some(Guernsey),
            b"GH" => Some(Ghana),
            b"GHA" => Some(Ghana),
            b"GI" => Some(Gibraltar),
            b"GIB" => Some(Gibraltar),
            b"GIN" => Some(Guinea),
            b"GN" => Some(Guinea),
            b"GL" => Some(Greenland),
            b"GRL" => Some(Greenland),
            b"GLP" => Some(Guadeloupe),
            b"GP" => Some(Guadeloupe),
            b"GM" => Some(CodeGM),
            b"GMB" => Some(CodeGM),
            b"GNB" => Some(GuineaBissau),
            b"GW" => Some(GuineaBissau),
            b"GNQ" => Some(EquatorialGuinea),
            b"GQ" => Some(EquatorialGuinea),
            b"GR" => Some(Greece),
            b"GRC" => Some(Greece),
            b"GS" => Some(SouthGeorgiaAndTheSouthSandwichIslands),
            b"SGS" => Some(SouthGeorgiaAndTheSouthSandwichIslands),
            b"GT" => Some(Guatemala),
            b"GTM" => Some(Guatemala),
            b"GU" => Some(Guam),
            b"GUM" => Some(Guam),
            b"GUY" => Some(Guyana),
            b"GY" => Some(Guyana),
            b"HK" => Some(HongKong),
            b"HKG" => Some(HongKong),
            b"HM" => Some(HeardIslandAndMcDonaldIslands),
            b"HMD" => Some(HeardIslandAndMcDonaldIslands),
            b"HN" => Some(Honduras),
            b"HND" => Some(Honduras),
            b"HR" => Some(Croatia),
            b"HRV" => Some(Croatia),
            b"HT" => Some(Haiti),
            b"HTI" => Some(Haiti),
            b"HU" => Some(Hungary),
            b"HUN" => Some(Hungary),
            b"ID" => Some(Indonesia),
            b"IDN" => Some(Indonesia),
            b"IE" => Some(Ireland),
            b"IRL" => Some(Ireland),
            b"IL" => Some(Israel),
            b"ISR" => Some(Israel),
            b"IM" => Some(IsleOfMan),
            b"IMN" => Some(IsleOfMan),
            b"IN" => Some(India),
            b"IND" => Some(India),
            b"IO" => Some(CodeIO),
            b"IOT" => Some(CodeIO),
            b"IQ" => Some(Iraq),
            b"IRQ" => Some(Iraq),
            b"IR" => Some(CodeIR),
            b"IRN" => Some(CodeIR),
            b"IS" => Some(Iceland),
            b"ISL" => Some(Iceland),
            b"IT" => Some(Italy),
            b"ITA" => Some(Italy),
            b"JAM" => Some(Jamaica),
            b"JM" => Some(Jamaica),
            b"JE" => Some(Jersey),
            b"JEY" => Some(Jersey),
            b"JO" => Some(Jordan),
            b"JOR" => Some(Jordan),
            b"JP" => Some(Japan),
            b"JPN" => Some(Japan),
            b"KAZ" => Some(Kazakhstan),
            b"KZ" => Some(Kazakhstan),
            b"KE" => Some(Kenya),
            b"KEN" => Some(Kenya),
            b"KG" => Some(Kyrgyzstan),
            b"KGZ" => Some(Kyrgyzstan),
            b"KH" => Some(Cambodia),
            b"KHM" => Some(Cambodia),
            b"KI" => Some(Kiribati),
            b"KIR" => Some(Kiribati),
            b"KN" => Some(SaintKittsAndNevis),
            b"KNA" => Some(SaintKittsAndNevis),
            b"KOR" => Some(CodeKOR),
            b"KR" => Some(CodeKOR),
            b"KP" => Some(CodeKP),
            b"PRK" => Some(CodeKP),
            b"KW" => Some(Kuwait),
            b"KWT" => Some(Kuwait),
            b"LA" => Some(CodeLA),
            b"LAO" => Some(CodeLA),
            b"LB" => Some(Lebanon),
            b"LBN" => Some(Lebanon),
            b"LBR" => Some(Liberia),
            b"LR" => Some(Liberia),
            b"LBY" => Some(Libya),
            b"LY" => Some(Libya),
            b"LC" => Some(SaintLucia),
            b"LCA" => Some(SaintLucia),
            b"LI" => Some(Liechtenstein),
            b"LIE" => Some(Liechtenstein),
            b"LK" => Some(SriLanka),
            b"LKA" => Some(SriLanka),
            b"LS" => Some(Lesotho),
            b"LSO" => Some(Lesotho),
            b"LT" => Some(Lithuania),
            b"LTU" => Some(Lithuania),
            b"LU" => Some(Luxembourg),
            b"LUX" => Some(Luxembourg),
            b"LV" => Some(Latvia),
            b"LVA" => Some(Latvia),
            b"MA" => Some(Morocco),
            b"MAR" => Some(Morocco),
            b"MAC" => Some(Macao),
            b"MO" => Some(Macao),
            b"MAF" => Some(CodeMAF),
            b"MF" => Some(CodeMAF),
            b"MC" => Some(Monaco),
            b"MCO" => Some(Monaco),
            b"MD" => Some(CodeMD),
            b"MDA" => Some(CodeMD),
            b"MDG" => Some(Madagascar),
            b"MG" => Some(Madagascar),
            b"MDV" => Some(Maldives),
            b"MV" => Some(Maldives),
            b"ME" => Some(Montenegro),
            b"MNE" => Some(Montenegro),
            b"MEX" => Some(Mexico),
            b"MX" => Some(Mexico),
            b"MH" => Some(CodeMH),
            b"MHL" => Some(CodeMH),
            b"MK" => Some(NorthMacedonia),
            b"MKD" => Some(NorthMacedonia),
            b"ML" => Some(Mali),
            b"MLI" => Some(Mali),
            b"MLT" => Some(Malta),
            b"MT" => Some(Malta),
            b"MM" => Some(Myanmar),
            b"MMR" => Some(Myanmar),
            b"MN" => Some(Mongolia),
            b"MNG" => Some(Mongolia),
            b"MNP" => Some(CodeMNP),
            b"MP" => Some(CodeMNP),
            b"MOZ" => Some(Mozambique),
            b"MZ" => Some(Mozambique),
            b"MQ" => Some(Martinique),
            b"MTQ" => Some(Martinique),
            b"MR" => Some(Mauritania),
            b"MRT" => Some(Mauritania),
            b"MS" => Some(Montserrat),
            b"MSR" => Some(Montserrat),
            b"MU" => Some(Mauritius),
            b"MUS" => Some(Mauritius),
            b"MW" => Some(Malawi),
            b"MWI" => Some(Malawi),
            b"MY" => Some(Malaysia),
            b"MYS" => Some(Malaysia),
            b"MYT" => Some(Mayotte),
            b"YT" => Some(Mayotte),
            b"NA" => Some(Namibia),
            b"NAM" => Some(Namibia),
            b"NC" => Some(NewCaledonia),
            b"NCL" => Some(NewCaledonia),
            b"NE" => Some(CodeNE),
            b"NER" => Some(CodeNE),
            b"NF" => Some(NorfolkIsland),
            b"NFK" => Some(NorfolkIsland),
            b"NG" => Some(Nigeria),
            b"NGA" => Some(Nigeria),
            b"NI" => Some(Nicaragua),
            b"NIC" => Some(Nicaragua),
            b"NIU" => Some(Niue),
            b"NU" => Some(Niue),
            b"NL" => Some(CodeNL),
            b"NLD" => Some(CodeNL),
            b"NO" => Some(Norway),
            b"NOR" => Some(Norway),
            b"NP" => Some(Nepal),
            b"NPL" => Some(Nepal),
            b"NR" => Some(Nauru),
            b"NRU" => Some(Nauru),
            b"NZ" => Some(NewZealand),
            b"NZL" => Some(NewZealand),
            b"OM" => Some(Oman),
            b"OMN" => Some(Oman),
            b"PA" => Some(Panama),
            b"PAN" => Some(Panama),
            b"PAK" => Some(Pakistan),
            b"PK" => Some(Pakistan),
            b"PCN" => Some(Pitcairn),
            b"PN" => Some(Pitcairn),
            b"PE" => Some(Peru),
            b"PER" => Some(Peru),
            b"PF" => Some(FrenchPolynesia),
            b"PYF" => Some(FrenchPolynesia),
            b"PG" => Some(PapuaNewGuinea),
            b"PNG" => Some(PapuaNewGuinea),
            b"PH" => Some(CodePH),
            b"PHL" => Some(CodePH),
            b"PL" => Some(Poland),
            b"POL" => Some(Poland),
            b"PLW" => Some(Palau),
            b"PW" => Some(Palau),
            b"PM" => Some(SaintPierreAndMiquelon),
            b"SPM" => Some(SaintPierreAndMiquelon),
            b"PR" => Some(PuertoRico),
            b"PRI" => Some(PuertoRico),
            b"PRT" => Some(Portugal),
            b"PT" => Some(Portugal),
            b"PRY" => Some(Paraguay),
            b"PY" => Some(Paraguay),
            b"PS" => Some(CodePS),
            b"PSE" => Some(CodePS),
            b"QA" => Some(Qatar),
            b"QAT" => Some(Qatar),
            b"RE" => Some(Reunion),
            b"REU" => Some(Reunion),
            b"RO" => Some(Romania),
            b"ROU" => Some(Romania),
            b"RS" => Some(Serbia),
            b"SRB" => Some(Serbia),
            b"RU" => Some(CodeRU),
            b"RUS" => Some(CodeRU),
            b"RW" => Some(Rwanda),
            b"RWA" => Some(Rwanda),
            b"SA" => Some(SaudiArabia),
            b"SAU" => Some(SaudiArabia),
            b"SB" => Some(SolomonIslands),
            b"SLB" => Some(SolomonIslands),
            b"SC" => Some(Seychelles),
            b"SYC" => Some(Seychelles),
            b"SD" => Some(CodeSD),
            b"SDN" => Some(CodeSD),
            b"SE" => Some(Sweden),
            b"SWE" => Some(Sweden),
            b"SEN" => Some(Senegal),
            b"SN" => Some(Senegal),
            b"SG" => Some(Singapore),
            b"SGP" => Some(Singapore),
            b"SH" => Some(CodeSH),
            b"SHN" => Some(CodeSH),
            b"SI" => Some(Slovenia),
            b"SVN" => Some(Slovenia),
            b"SJ" => Some(SvalbardAndJanMayen),
            b"SJM" => Some(SvalbardAndJanMayen),
            b"SK" => Some(Slovakia),
            b"SVK" => Some(Slovakia),
            b"SL" => Some(SierraLeone),
            b"SLE" => Some(SierraLeone),
            b"SLV" => Some(ElSalvador),
            b"SV" => Some(ElSalvador),
            b"SM" => Some(SanMarino),
            b"SMR" => Some(SanMarino),
            b"SO" => Some(Somalia),
            b"SOM" => Some(Somalia),
            b"SR" => Some(Suriname),
            b"SUR" => Some(Suriname),
            b"SS" => Some(SouthSudan),
            b"SSD" => Some(SouthSudan),
            b"ST" => Some(SaoTomeAndPrincipe),
            b"STP" => Some(SaoTomeAndPrincipe),
            b"SWZ" => Some(Eswatini),
            b"SZ" => Some(Eswatini),
            b"SX" => Some(CodeSX),
            b"SXM" => Some(CodeSX),
            b"SY" => Some(CodeSY),
            b"SYR" => Some(CodeSY),
            b"TC" => Some(CodeTC),
            b"TCA" => Some(CodeTC),
            b"TCD" => Some(Chad),
            b"TD" => Some(Chad),
            b"TG" => Some(Togo),
            b"TGO" => Some(Togo),
            b"TH" => Some(Thailand),
            b"THA" => Some(Thailand),
            b"TJ" => Some(Tajikistan),
            b"TJK" => Some(Tajikistan),
            b"TK" => Some(Tokelau),
            b"TKL" => Some(Tokelau),
            b"TKM" => Some(Turkmenistan),
            b"TM" => Some(Turkmenistan),
            b"TL" => Some(TimorLeste),
            b"TLS" => Some(TimorLeste),
            b"TN" => Some(Tunisia),
            b"TUN" => Some(Tunisia),
            b"TO" => Some(Tonga),
            b"TON" => Some(Tonga),
            b"TR" => Some(Türkiye),
            b"TUR" => Some(Türkiye),
            b"TT" => Some(TrinidadAndTobago),
            b"TTO" => Some(TrinidadAndTobago),
            b"TUV" => Some(Tuvalu),
            b"TV" => Some(Tuvalu),
            b"TW" => Some(CodeTW),
            b"TWN" => Some(CodeTW),
            b"TZ" => Some(CodeTZ),
            b"TZA" => Some(CodeTZ),
            b"UA" => Some(Ukraine),
            b"UKR" => Some(Ukraine),
            b"UG" => Some(Uganda),
            b"UGA" => Some(Uganda),
            b"UM" => Some(CodeUM),
            b"UMI" => Some(CodeUM),
            b"URY" => Some(Uruguay),
            b"UY" => Some(Uruguay),
            b"US" => Some(CodeUS),
            b"USA" => Some(CodeUS),
            b"UZ" => Some(Uzbekistan),
            b"UZB" => Some(Uzbekistan),
            b"VA" => Some(CodeVA),
            b"VAT" => Some(CodeVA),
            b"VC" => Some(SaintVincentAndTheGrenadines),
            b"VCT" => Some(SaintVincentAndTheGrenadines),
            b"VE" => Some(CodeVE),
            b"VEN" => Some(CodeVE),
            b"VG" => Some(CodeVG),
            b"VGB" => Some(CodeVG),
            b"VI" => Some(CodeVI),
            b"VIR" => Some(CodeVI),
            b"VN" => Some(VietNam),
            b"VNM" => Some(VietNam),
            b"VU" => Some(Vanuatu),
            b"VUT" => Some(Vanuatu),
            b"WF" => Some(WallisAndFutuna),
            b"WLF" => Some(WallisAndFutuna),
            b"WS" => Some(Samoa),
            b"WSM" => Some(Samoa),
            b"YE" => Some(Yemen),
            b"YEM" => Some(Yemen),
            b"ZA" => Some(SouthAfrica),
            b"ZAF" => Some(SouthAfrica),
            b"ZM" => Some(Zambia),
            b"ZMB" => Some(Zambia),
            b"ZW" => Some(Zimbabwe),
            b"ZWE" => Some(Zimbabwe),
            _ => None,
        }
    }
    fn description(&self) -> &str {
        use CountryCode::*;
        match self {
            Aruba => "Aruba",
            Andorra => "Andorra",
            CodeAE => "United Arab Emirates (the)",
            Afghanistan => "Afghanistan",
            AntiguaAndBarbuda => "Antigua and Barbuda",
            Angola => "Angola",
            Anguilla => "Anguilla",
            Albania => "Albania",
            ÅlandIslands => "Åland Islands",
            Armenia => "Armenia",
            Antarctica => "Antarctica",
            Argentina => "Argentina",
            AmericanSamoa => "American Samoa",
            Austria => "Austria",
            CodeATF => "French Southern Territories (the)",
            Australia => "Australia",
            Azerbaijan => "Azerbaijan",
            BosniaAndHerzegovina => "Bosnia and Herzegovina",
            Barbados => "Barbados",
            Bangladesh => "Bangladesh",
            Burundi => "Burundi",
            Belgium => "Belgium",
            Benin => "Benin",
            CodeBES => "Bonaire, Sint Eustatius and Saba",
            BurkinaFaso => "Burkina Faso",
            Bulgaria => "Bulgaria",
            Bahrain => "Bahrain",
            CodeBHS => "Bahamas (the)",
            SaintBarthelemy => "Saint Barthélemy",
            Belarus => "Belarus",
            Belize => "Belize",
            Bermuda => "Bermuda",
            BruneiDarussalam => "Brunei Darussalam",
            CodeBO => "Bolivia (Plurinational State of)",
            Brazil => "Brazil",
            Bhutan => "Bhutan",
            BouvetIsland => "Bouvet Island",
            Botswana => "Botswana",
            Canada => "Canada",
            CodeCAF => "Central African Republic (the)",
            CodeCC => "Cocos (Keeling) Islands (the)",
            CodeCD => "Congo (the Democratic Republic of the)",
            CodeCG => "Congo (the)",
            Switzerland => "Switzerland",
            Chile => "Chile",
            China => "China",
            CôteDIvoire => "Côte d'Ivoire",
            CodeCK => "Cook Islands (the)",
            Cameroon => "Cameroon",
            Colombia => "Colombia",
            CodeCOM => "Comoros (the)",
            CaboVerde => "Cabo Verde",
            CostaRica => "Costa Rica",
            Cuba => "Cuba",
            Curaçao => "Curaçao",
            ChristmasIsland => "Christmas Island",
            Cyprus => "Cyprus",
            CodeCYM => "Cayman Islands (the)",
            Czechia => "Czechia",
            Germany => "Germany",
            Djibouti => "Djibouti",
            Denmark => "Denmark",
            Dominica => "Dominica",
            CodeDO => "Dominican Republic (the)",
            Algeria => "Algeria",
            Ecuador => "Ecuador",
            Estonia => "Estonia",
            Egypt => "Egypt",
            CodeEH => "Western Sahara*",
            Eritrea => "Eritrea",
            Spain => "Spain",
            Ethiopia => "Ethiopia",
            Finland => "Finland",
            Fiji => "Fiji",
            CodeFK => "Falkland Islands (the) [Malvinas]",
            CodeFM => "Micronesia (Federated States of)",
            CodeFO => "Faroe Islands (the)",
            France => "France",
            Gabon => "Gabon",
            CodeGB => "United Kingdom of Great Britain and Northern Ireland (the)",
            Grenada => "Grenada",
            Georgia => "Georgia",
            FrenchGuiana => "French Guiana",
            Guernsey => "Guernsey",
            Ghana => "Ghana",
            Gibraltar => "Gibraltar",
            Guinea => "Guinea",
            Greenland => "Greenland",
            Guadeloupe => "Guadeloupe",
            CodeGM => "Gambia (the)",
            GuineaBissau => "Guinea-Bissau",
            EquatorialGuinea => "Equatorial Guinea",
            Greece => "Greece",
            SouthGeorgiaAndTheSouthSandwichIslands => {
                "South Georgia and the South Sandwich Islands"
            }
            Guatemala => "Guatemala",
            Guam => "Guam",
            Guyana => "Guyana",
            HongKong => "Hong Kong",
            HeardIslandAndMcDonaldIslands => "Heard Island and McDonald Islands",
            Honduras => "Honduras",
            Croatia => "Croatia",
            Haiti => "Haiti",
            Hungary => "Hungary",
            Indonesia => "Indonesia",
            Ireland => "Ireland",
            Israel => "Israel",
            IsleOfMan => "Isle of Man",
            India => "India",
            CodeIO => "British Indian Ocean Territory (the)",
            Iraq => "Iraq",
            CodeIR => "Iran (Islamic Republic of)",
            Iceland => "Iceland",
            Italy => "Italy",
            Jamaica => "Jamaica",
            Jersey => "Jersey",
            Jordan => "Jordan",
            Japan => "Japan",
            Kazakhstan => "Kazakhstan",
            Kenya => "Kenya",
            Kyrgyzstan => "Kyrgyzstan",
            Cambodia => "Cambodia",
            Kiribati => "Kiribati",
            SaintKittsAndNevis => "Saint Kitts and Nevis",
            CodeKOR => "Korea (the Republic of)",
            CodeKP => "Korea (the Democratic People's Republic of)",
            Kuwait => "Kuwait",
            CodeLA => "Lao People's Democratic Republic (the)",
            Lebanon => "Lebanon",
            Liberia => "Liberia",
            Libya => "Libya",
            SaintLucia => "Saint Lucia",
            Liechtenstein => "Liechtenstein",
            SriLanka => "Sri Lanka",
            Lesotho => "Lesotho",
            Lithuania => "Lithuania",
            Luxembourg => "Luxembourg",
            Latvia => "Latvia",
            Morocco => "Morocco",
            Macao => "Macao",
            CodeMAF => "Saint Martin (French part)",
            Monaco => "Monaco",
            CodeMD => "Moldova (the Republic of)",
            Madagascar => "Madagascar",
            Maldives => "Maldives",
            Montenegro => "Montenegro",
            Mexico => "Mexico",
            CodeMH => "Marshall Islands (the)",
            NorthMacedonia => "North Macedonia",
            Mali => "Mali",
            Malta => "Malta",
            Myanmar => "Myanmar",
            Mongolia => "Mongolia",
            CodeMNP => "Northern Mariana Islands (the)",
            Mozambique => "Mozambique",
            Martinique => "Martinique",
            Mauritania => "Mauritania",
            Montserrat => "Montserrat",
            Mauritius => "Mauritius",
            Malawi => "Malawi",
            Malaysia => "Malaysia",
            Mayotte => "Mayotte",
            Namibia => "Namibia",
            NewCaledonia => "New Caledonia",
            CodeNE => "Niger (the)",
            NorfolkIsland => "Norfolk Island",
            Nigeria => "Nigeria",
            Nicaragua => "Nicaragua",
            Niue => "Niue",
            CodeNL => "Netherlands (the)",
            Norway => "Norway",
            Nepal => "Nepal",
            Nauru => "Nauru",
            NewZealand => "New Zealand",
            Oman => "Oman",
            Panama => "Panama",
            Pakistan => "Pakistan",
            Pitcairn => "Pitcairn",
            Peru => "Peru",
            FrenchPolynesia => "French Polynesia",
            PapuaNewGuinea => "Papua New Guinea",
            CodePH => "Philippines (the)",
            Poland => "Poland",
            Palau => "Palau",
            SaintPierreAndMiquelon => "Saint Pierre and Miquelon",
            PuertoRico => "Puerto Rico",
            Portugal => "Portugal",
            Paraguay => "Paraguay",
            CodePS => "Palestine, State of",
            Qatar => "Qatar",
            Reunion => "Réunion",
            Romania => "Romania",
            Serbia => "Serbia",
            CodeRU => "Russian Federation (the)",
            Rwanda => "Rwanda",
            SaudiArabia => "Saudi Arabia",
            SolomonIslands => "Solomon Islands",
            Seychelles => "Seychelles",
            CodeSD => "Sudan (the)",
            Sweden => "Sweden",
            Senegal => "Senegal",
            Singapore => "Singapore",
            CodeSH => "Saint Helena, Ascension and Tristan da Cunha",
            Slovenia => "Slovenia",
            SvalbardAndJanMayen => "Svalbard and Jan Mayen",
            Slovakia => "Slovakia",
            SierraLeone => "Sierra Leone",
            ElSalvador => "El Salvador",
            SanMarino => "San Marino",
            Somalia => "Somalia",
            Suriname => "Suriname",
            SouthSudan => "South Sudan",
            SaoTomeAndPrincipe => "Sao Tome and Principe",
            Eswatini => "Eswatini",
            CodeSX => "Sint Maarten (Dutch part)",
            CodeSY => "Syrian Arab Republic (the)",
            CodeTC => "Turks and Caicos Islands (the)",
            Chad => "Chad",
            Togo => "Togo",
            Thailand => "Thailand",
            Tajikistan => "Tajikistan",
            Tokelau => "Tokelau",
            Turkmenistan => "Turkmenistan",
            TimorLeste => "Timor-Leste",
            Tunisia => "Tunisia",
            Tonga => "Tonga",
            Türkiye => "Türkiye",
            TrinidadAndTobago => "Trinidad and Tobago",
            Tuvalu => "Tuvalu",
            CodeTW => "Taiwan (Province of China)",
            CodeTZ => "Tanzania, the United Republic of",
            Ukraine => "Ukraine",
            Uganda => "Uganda",
            CodeUM => "United States Minor Outlying Islands (the)",
            Uruguay => "Uruguay",
            CodeUS => "United States of America (the)",
            Uzbekistan => "Uzbekistan",
            CodeVA => "Holy See (the)",
            SaintVincentAndTheGrenadines => "Saint Vincent and the Grenadines",
            CodeVE => "Venezuela (Bolivarian Republic of)",
            CodeVG => "Virgin Islands (British)",
            CodeVI => "Virgin Islands (U.S.)",
            VietNam => "Viet Nam",
            Vanuatu => "Vanuatu",
            WallisAndFutuna => "Wallis and Futuna",
            Samoa => "Samoa",
            Yemen => "Yemen",
            SouthAfrica => "South Africa",
            Zambia => "Zambia",
            Zimbabwe => "Zimbabwe",
        }
    }
    fn from_description(description: &str) -> Option<CountryCode> {
        {
            use CountryCode::*;
            match description {
                "Aruba" => Some(Aruba),
                "Andorra" => Some(Andorra),
                "United Arab Emirates (the)" => Some(CodeAE),
                "Afghanistan" => Some(Afghanistan),
                "Antigua and Barbuda" => Some(AntiguaAndBarbuda),
                "Angola" => Some(Angola),
                "Anguilla" => Some(Anguilla),
                "Albania" => Some(Albania),
                "Åland Islands" => Some(ÅlandIslands),
                "Armenia" => Some(Armenia),
                "Antarctica" => Some(Antarctica),
                "Argentina" => Some(Argentina),
                "American Samoa" => Some(AmericanSamoa),
                "Austria" => Some(Austria),
                "French Southern Territories (the)" => Some(CodeATF),
                "Australia" => Some(Australia),
                "Azerbaijan" => Some(Azerbaijan),
                "Bosnia and Herzegovina" => Some(BosniaAndHerzegovina),
                "Barbados" => Some(Barbados),
                "Bangladesh" => Some(Bangladesh),
                "Burundi" => Some(Burundi),
                "Belgium" => Some(Belgium),
                "Benin" => Some(Benin),
                "Bonaire, Sint Eustatius and Saba" => Some(CodeBES),
                "Burkina Faso" => Some(BurkinaFaso),
                "Bulgaria" => Some(Bulgaria),
                "Bahrain" => Some(Bahrain),
                "Bahamas (the)" => Some(CodeBHS),
                "Saint Barthélemy" => Some(SaintBarthelemy),
                "Belarus" => Some(Belarus),
                "Belize" => Some(Belize),
                "Bermuda" => Some(Bermuda),
                "Brunei Darussalam" => Some(BruneiDarussalam),
                "Bolivia (Plurinational State of)" => Some(CodeBO),
                "Brazil" => Some(Brazil),
                "Bhutan" => Some(Bhutan),
                "Bouvet Island" => Some(BouvetIsland),
                "Botswana" => Some(Botswana),
                "Canada" => Some(Canada),
                "Central African Republic (the)" => Some(CodeCAF),
                "Cocos (Keeling) Islands (the)" => Some(CodeCC),
                "Congo (the Democratic Republic of the)" => Some(CodeCD),
                "Congo (the)" => Some(CodeCG),
                "Switzerland" => Some(Switzerland),
                "Chile" => Some(Chile),
                "China" => Some(China),
                "Côte d'Ivoire" => Some(CôteDIvoire),
                "Cook Islands (the)" => Some(CodeCK),
                "Cameroon" => Some(Cameroon),
                "Colombia" => Some(Colombia),
                "Comoros (the)" => Some(CodeCOM),
                "Cabo Verde" => Some(CaboVerde),
                "Costa Rica" => Some(CostaRica),
                "Cuba" => Some(Cuba),
                "Curaçao" => Some(Curaçao),
                "Christmas Island" => Some(ChristmasIsland),
                "Cyprus" => Some(Cyprus),
                "Cayman Islands (the)" => Some(CodeCYM),
                "Czechia" => Some(Czechia),
                "Germany" => Some(Germany),
                "Djibouti" => Some(Djibouti),
                "Denmark" => Some(Denmark),
                "Dominica" => Some(Dominica),
                "Dominican Republic (the)" => Some(CodeDO),
                "Algeria" => Some(Algeria),
                "Ecuador" => Some(Ecuador),
                "Estonia" => Some(Estonia),
                "Egypt" => Some(Egypt),
                "Western Sahara*" => Some(CodeEH),
                "Eritrea" => Some(Eritrea),
                "Spain" => Some(Spain),
                "Ethiopia" => Some(Ethiopia),
                "Finland" => Some(Finland),
                "Fiji" => Some(Fiji),
                "Falkland Islands (the) [Malvinas]" => Some(CodeFK),
                "Micronesia (Federated States of)" => Some(CodeFM),
                "Faroe Islands (the)" => Some(CodeFO),
                "France" => Some(France),
                "Gabon" => Some(Gabon),
                "United Kingdom of Great Britain and Northern Ireland (the)" => {
                    Some(CodeGB)
                }
                "Grenada" => Some(Grenada),
                "Georgia" => Some(Georgia),
                "French Guiana" => Some(FrenchGuiana),
                "Guernsey" => Some(Guernsey),
                "Ghana" => Some(Ghana),
                "Gibraltar" => Some(Gibraltar),
                "Guinea" => Some(Guinea),
                "Greenland" => Some(Greenland),
                "Guadeloupe" => Some(Guadeloupe),
                "Gambia (the)" => Some(CodeGM),
                "Guinea-Bissau" => Some(GuineaBissau),
                "Equatorial Guinea" => Some(EquatorialGuinea),
                "Greece" => Some(Greece),
                "South Georgia and the South Sandwich Islands" => {
                    Some(SouthGeorgiaAndTheSouthSandwichIslands)
                }
                "Guatemala" => Some(Guatemala),
                "Guam" => Some(Guam),
                "Guyana" => Some(Guyana),
                "Hong Kong" => Some(HongKong),
                "Heard Island and McDonald Islands" => {
                    Some(HeardIslandAndMcDonaldIslands)
                }
                "Honduras" => Some(Honduras),
                "Croatia" => Some(Croatia),
                "Haiti" => Some(Haiti),
                "Hungary" => Some(Hungary),
                "Indonesia" => Some(Indonesia),
                "Ireland" => Some(Ireland),
                "Israel" => Some(Israel),
                "Isle of Man" => Some(IsleOfMan),
                "India" => Some(India),
                "British Indian Ocean Territory (the)" => Some(CodeIO),
                "Iraq" => Some(Iraq),
                "Iran (Islamic Republic of)" => Some(CodeIR),
                "Iceland" => Some(Iceland),
                "Italy" => Some(Italy),
                "Jamaica" => Some(Jamaica),
                "Jersey" => Some(Jersey),
                "Jordan" => Some(Jordan),
                "Japan" => Some(Japan),
                "Kazakhstan" => Some(Kazakhstan),
                "Kenya" => Some(Kenya),
                "Kyrgyzstan" => Some(Kyrgyzstan),
                "Cambodia" => Some(Cambodia),
                "Kiribati" => Some(Kiribati),
                "Saint Kitts and Nevis" => Some(SaintKittsAndNevis),
                "Korea (the Republic of)" => Some(CodeKOR),
                "Korea (the Democratic People's Republic of)" => Some(CodeKP),
                "Kuwait" => Some(Kuwait),
                "Lao People's Democratic Republic (the)" => Some(CodeLA),
                "Lebanon" => Some(Lebanon),
                "Liberia" => Some(Liberia),
                "Libya" => Some(Libya),
                "Saint Lucia" => Some(SaintLucia),
                "Liechtenstein" => Some(Liechtenstein),
                "Sri Lanka" => Some(SriLanka),
                "Lesotho" => Some(Lesotho),
                "Lithuania" => Some(Lithuania),
                "Luxembourg" => Some(Luxembourg),
                "Latvia" => Some(Latvia),
                "Morocco" => Some(Morocco),
                "Macao" => Some(Macao),
                "Saint Martin (French part)" => Some(CodeMAF),
                "Monaco" => Some(Monaco),
                "Moldova (the Republic of)" => Some(CodeMD),
                "Madagascar" => Some(Madagascar),
                "Maldives" => Some(Maldives),
                "Montenegro" => Some(Montenegro),
                "Mexico" => Some(Mexico),
                "Marshall Islands (the)" => Some(CodeMH),
                "North Macedonia" => Some(NorthMacedonia),
                "Mali" => Some(Mali),
                "Malta" => Some(Malta),
                "Myanmar" => Some(Myanmar),
                "Mongolia" => Some(Mongolia),
                "Northern Mariana Islands (the)" => Some(CodeMNP),
                "Mozambique" => Some(Mozambique),
                "Martinique" => Some(Martinique),
                "Mauritania" => Some(Mauritania),
                "Montserrat" => Some(Montserrat),
                "Mauritius" => Some(Mauritius),
                "Malawi" => Some(Malawi),
                "Malaysia" => Some(Malaysia),
                "Mayotte" => Some(Mayotte),
                "Namibia" => Some(Namibia),
                "New Caledonia" => Some(NewCaledonia),
                "Niger (the)" => Some(CodeNE),
                "Norfolk Island" => Some(NorfolkIsland),
                "Nigeria" => Some(Nigeria),
                "Nicaragua" => Some(Nicaragua),
                "Niue" => Some(Niue),
                "Netherlands (the)" => Some(CodeNL),
                "Norway" => Some(Norway),
                "Nepal" => Some(Nepal),
                "Nauru" => Some(Nauru),
                "New Zealand" => Some(NewZealand),
                "Oman" => Some(Oman),
                "Panama" => Some(Panama),
                "Pakistan" => Some(Pakistan),
                "Pitcairn" => Some(Pitcairn),
                "Peru" => Some(Peru),
                "French Polynesia" => Some(FrenchPolynesia),
                "Papua New Guinea" => Some(PapuaNewGuinea),
                "Philippines (the)" => Some(CodePH),
                "Poland" => Some(Poland),
                "Palau" => Some(Palau),
                "Saint Pierre and Miquelon" => Some(SaintPierreAndMiquelon),
                "Puerto Rico" => Some(PuertoRico),
                "Portugal" => Some(Portugal),
                "Paraguay" => Some(Paraguay),
                "Palestine, State of" => Some(CodePS),
                "Qatar" => Some(Qatar),
                "Réunion" => Some(Reunion),
                "Romania" => Some(Romania),
                "Serbia" => Some(Serbia),
                "Russian Federation (the)" => Some(CodeRU),
                "Rwanda" => Some(Rwanda),
                "Saudi Arabia" => Some(SaudiArabia),
                "Solomon Islands" => Some(SolomonIslands),
                "Seychelles" => Some(Seychelles),
                "Sudan (the)" => Some(CodeSD),
                "Sweden" => Some(Sweden),
                "Senegal" => Some(Senegal),
                "Singapore" => Some(Singapore),
                "Saint Helena, Ascension and Tristan da Cunha" => Some(CodeSH),
                "Slovenia" => Some(Slovenia),
                "Svalbard and Jan Mayen" => Some(SvalbardAndJanMayen),
                "Slovakia" => Some(Slovakia),
                "Sierra Leone" => Some(SierraLeone),
                "El Salvador" => Some(ElSalvador),
                "San Marino" => Some(SanMarino),
                "Somalia" => Some(Somalia),
                "Suriname" => Some(Suriname),
                "South Sudan" => Some(SouthSudan),
                "Sao Tome and Principe" => Some(SaoTomeAndPrincipe),
                "Eswatini" => Some(Eswatini),
                "Sint Maarten (Dutch part)" => Some(CodeSX),
                "Syrian Arab Republic (the)" => Some(CodeSY),
                "Turks and Caicos Islands (the)" => Some(CodeTC),
                "Chad" => Some(Chad),
                "Togo" => Some(Togo),
                "Thailand" => Some(Thailand),
                "Tajikistan" => Some(Tajikistan),
                "Tokelau" => Some(Tokelau),
                "Turkmenistan" => Some(Turkmenistan),
                "Timor-Leste" => Some(TimorLeste),
                "Tunisia" => Some(Tunisia),
                "Tonga" => Some(Tonga),
                "Türkiye" => Some(Türkiye),
                "Trinidad and Tobago" => Some(TrinidadAndTobago),
                "Tuvalu" => Some(Tuvalu),
                "Taiwan (Province of China)" => Some(CodeTW),
                "Tanzania, the United Republic of" => Some(CodeTZ),
                "Ukraine" => Some(Ukraine),
                "Uganda" => Some(Uganda),
                "United States Minor Outlying Islands (the)" => Some(CodeUM),
                "Uruguay" => Some(Uruguay),
                "United States of America (the)" => Some(CodeUS),
                "Uzbekistan" => Some(Uzbekistan),
                "Holy See (the)" => Some(CodeVA),
                "Saint Vincent and the Grenadines" => Some(SaintVincentAndTheGrenadines),
                "Venezuela (Bolivarian Republic of)" => Some(CodeVE),
                "Virgin Islands (British)" => Some(CodeVG),
                "Virgin Islands (U.S.)" => Some(CodeVI),
                "Viet Nam" => Some(VietNam),
                "Vanuatu" => Some(Vanuatu),
                "Wallis and Futuna" => Some(WallisAndFutuna),
                "Samoa" => Some(Samoa),
                "Yemen" => Some(Yemen),
                "South Africa" => Some(SouthAfrica),
                "Zambia" => Some(Zambia),
                "Zimbabwe" => Some(Zimbabwe),
                _ => None,
            }
        }
    }
}
impl Serialize for CountryCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: ser::Serializer,
    {
        let value = if serializer.is_human_readable() {
            self.description()
        } else {
            self.code()
        };
        serializer.serialize_str(value)
    }
}
struct Visitor;
impl<'de> de::Visitor<'de> for Visitor {
    type Value = CountryCode;
    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        formatter.write_str("Country Code")
    }
    fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        CountryCode::from_description(v)
            .ok_or_else(|| E::custom(format!("Invalid Country Code: {}", v)))
    }
    fn visit_bytes<E>(self, v: &[u8]) -> Result<Self::Value, E>
    where
        E: de::Error,
    {
        CountryCode::from_code(v)
            .ok_or_else(|| E::custom(
                format!("Invalid Country Code: {}", std::str::from_utf8(v).unwrap()),
            ))
    }
}
impl<'de> Deserialize<'de> for CountryCode {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: de::Deserializer<'de>,
    {
        if deserializer.is_human_readable() {
            deserializer.deserialize_str(Visitor)
        } else {
            deserializer.deserialize_bytes(Visitor)
        }
    }
}